name: Warp
author: Cuuky
version: 1.2.2
main: me.cuuky.Main
api-version: 1.19
commands:
    setwarp:
        permission: Warp.setwarp
    warp:
        permission: Warp.warp
    delwarp:
        permission: Warp.delwarp
    warplist:
        permission: Warp.warplist