name: Warp
author: Cuuky
version: 1.2.1
main: me.cuuky.Main
commands:
    setwarp:
        permission: Warp.setwarp
    warp:
        permission: Warp.warp
    delwarp:
        permission: Warp.delwarp
    warplist:
        permission: Warp.warplist